### ISSUE TITLE
Behavior changes based on presense of colorama

### ISSUE THREAD

**Issue by proximous** [borntyping/python-colorlog#40]
Without colorama installed, the provided ColoredFormatter will always use colors, even when redirected to a file (ie. $ ./command.py 2> error_out.txt)

When colorama is installed, colorama detects a non-tty, and strips the colors.

Since colorlog provides a TTYColoredFormater that will strip colors for a non-tty, the above behavior seems not only inconsistent, but unintended. (ie. the user chooses stripping for non-tty by choosing TTYColoredFormater instead of ColoredFormatter, not by having or not having colorama installed.)

I therefore suggest that the colorama init should be called as:
`colorama.init(strip=False)`
or minimally some other option should be available to colorlog users to 'force' colors or prevent stripping.

I like my logs to have color even when redirected to files.  Using 'less -R' let's you still benefit from the colors when reviewing the output.

**Comment by borntyping** [comment]
I think that makes sense - would you be willing to make a pull request implementing this?

**Comment by proximous** [comment]
Thanks. Can you update this ticket when it makes an official release on PyPi?

**Comment by dimrozakis** [comment]
Hi @borntyping. I'm still facing this issue. 

I have a python application running under `uwsgi`, configured to work with `colorlog`. Everything was working properly (logs were colored) until recently. The system now also includes `awscli` which pulls in `colorama` as a dependency. Since then, `uwsgi` logs are not colored. I can verify that uninstalling `colorama` fixes the coloring of logs.

The PR linked to this issue (#41) appears to be merged, but the change it introduced doesn't seem to be contained in the current version of `colorlog` (actually I couldn't even find that commit in the history).

@borntyping could you please consider reopening this issue and either reapply #41 or use some other method such as checking `sys.platform` and only using `colorama` under windows in order to address the problem?

**Comment by dimrozakis** [comment]
Hi @borntyping, did you perhaps have a chance to read my comment above? Is it possible to reopen this issue?

**Comment by borntyping** [comment]
Not sure what happened to the commit in #41. I don't currently have a setup that I can build and publish `colorlog` with, so I won't be able to fix this until next week.

**Comment by dimrozakis** [comment]
Hi @borntyping, are there any updates on this? The issue could easily be fixed by either reintroducing #41 (haven't tried it) or only importing and initializing `colorama` if `sys.platform == "win32"`. Thanks

**Comment by borntyping** [comment]
The commit from #41 has been merged and released as [4.3.0](https://pypi.org/project/colorlog/4.3.0/).

https://github.com/borntyping/python-colorlog/blob/master/colorlog/escape_codes.py#L14

**Comment by dimrozakis** [comment]
thanks @borntyping
