### ISSUE TITLE
Tests fail with newer versions of pytest

### ISSUE THREAD

**Issue by seifertm** [borntyping/python-colorlog#62]
I am currently trying to update the colorlog package for Gentoo Linux to v3.1.4. One of the devs ran into the issue that the tests didn't pass, whereas they passed on my machine. It looks like the version of `pytest` is responsible. I could reproduce test errors with `pytest-3.6.3` and `pytest-3.4.2`, but tests ran successfully with `pytest-3.2.2`.

Please see https://github.com/gentoo/gentoo/pull/9653#issuecomment-415395039 for log outputs and reference.

`pytest-3.2.2` will be dropped from the Gentoo package tree sooner or later. Is it possible to fix this issue?

**Comment by borntyping** [comment]
I'm guessing pytest has changed the way it captures output again. I can take a look when I have some time but can't provide an ETA for that.

**Comment by sbraz** [comment]
After a bit of research, I found the root cause of this issue: pytest 3.3 introduced a `logging` plugin which is disabled in `tox.ini`:
https://github.com/borntyping/python-colorlog/blob/5f7bf637fa8d973bba6ea13ad78d39f085b44b74/tox.ini#L29

The problem is that the PyPI tarballs for v3.1.4 don't contain tox.ini so when we run `pytest`, it fails.

**Comment by borntyping** [comment]
Released in [4.0.0](https://github.com/borntyping/python-colorlog/releases/tag/v4.0.0).
