### ISSUE TITLE
TTYColoredFormatter should drop every escape sequences, not only colors

### ISSUE THREAD

**Issue by sandrotosi** [borntyping/python-colorlog#71]
Hello,
currently using TTYColoredFormatter will only remove colors from the output, but if you definer your format with other codes (like _reset_ for example) than those sequences are still printed, producing a terrible output if you are redirecting to a file (f.e.)

could you make sure TTYColoredFormatter actually removes every escape sequence? thanks!

**Comment by borntyping** [comment]
`TTYColoredFormatter` doesn't remove anything - it just disables automatic reset characters and disables `log_color`. You're better off configuring your loggers differently if you're not running in a TTY.

**Comment by sandrotosi** [comment]
ok then, `TTYColoredFormatter` should also disable every other escape codes. the logic to show colored output or not is in `TTYColoredFormatter` (depending on the stream being a TTY) so why you suggest to use something else?

if you think this is not how colorlog should behave, just go ahead and close this issue

**Comment by tgpfeiffer** [comment]
I have the same issue as @sandrotosi here. I thought using the `TTYColoredFormatter` would resolve the issue of having to maintain two different configurations, but now my logfile looks like
```
[2019-10-30 10:11:53.563] [INFO[0m] xmlrpc[0m - xml rpc node: starting XML-RPC server
```
I understand that as the code currently works, just removing the reset characters won't work, because explicit color codes like `%(fg_cyan)s%(name)s%(reset)s` are still present in the non-TTY output, and so removing all resets would therefore color the whole message, I assume. So this suggestion,
> ok then, `TTYColoredFormatter` should also disable every other escape codes

sounds fairly reasonable to me.
